Add plugin for Avail
elizaOS/eliza pull request #1241
Opened 2024-12-19 15:54 UTC by robin-rrt

# Relates to:

N/A

# Risks

Low.
The main implementation risk is that the Plugin doesn't work as intended.

# Background

## What does this PR do?

[Avail](https://www.availproject.org/) aims to accelerate Web3's unification using its cutting-edge modular technology stack, which combines data availability, aggregation, and shared security.

In this version, the `transfer` and `submitData` actions are supported.

Multiple L2s are working with Avail to meet their data availability and interoperability needs.

## What kind of change is this?

Features (non-breaking change which adds functionality)

# Documentation changes needed?
Since Avail is a Substrate based network, and not EVM-compatible (cannot work with `plugin-evm`), it requires some docs to show how to submit data and transfer tokens.  I have updated the documentation accordingly in the README for the plugin.

# Testing

## Where should a reviewer start?

Most of the changes are in `plugin-avail`

## Detailed testing steps
- In `.env` you should set the value for `AVAIL_ADDRESS` (this is the public address for the agent account) and `AVAIL_SEED` (seed phrase for the same account).
- **Transfer AVAIL**
    - To test transfer function, you need tokens in your Avail account. On testnet, you can use the [Avail Faucet](https://faucet.avail.tools/). If you need more please ping me, and I can send it over. 
    - Run the agent and prompt it with: "send 1 AVAIL to <any other Avail account> " - e.g. `send 1 AVAIL to 5GWbvXjefEvXXETtKQH7YBsUaPc379KAQATW1eqeJT26cbsK`
    - Assuming everything goes smoothly the agent returns with the Tx Hash, and Block Hash. 
The tx hash can be checked on the Avail block explorer at https://avail-turing.subscan.io/
- **Submit Data**
    - To test data submission,  you need tokens in your Avail account to pay fees. On testnet, you can use the [Avail Faucet](https://faucet.avail.tools/). If you need more please ping me, and I can send it over. 
    - Run the agent and prompt it with: "Submit the following data to Avail <DATA>" - e.g. `Submit the following data to Avail "Hello World!"`
    - Assuming everything goes smoothly the agent returns with the Tx Hash, and Block Hash. 

## Discord username
RobinRRT

2024-12-20 04:17 UTC, odilitime requested changes

2024-12-20 04:17 UTC, odilitime commented on agent/src/index.ts
> +            getSecret(character, "AVAIL_APP_ID") ? availPlugin : null,
you probably don't want to add it twice

```
getSecret(character, "AVAIL_SEED") && getSecret(character, "AVAIL_APP_ID") ? availPlugin : null,
```

2024-12-20 11:50 UTC, robin-rrt commented on agent/src/index.ts
> +            getSecret(character, "AVAIL_APP_ID") ? availPlugin : null,
gotcha.

2024-12-20 11:51 UTC, robin-rrt commented
@odilitime what documentation would you like to see more for the plugin? I see you put a tag for more documentation

2024-12-20 17:55 UTC, robin-rrt commented
@odilitime addressed changes. please review

2024-12-29 03:04 UTC, robin-rrt commented
Hey @odilitime checking in if you please review and merge the plugin

2024-12-29 03:12 UTC, odilitime commented
You don’t need to do the docs, the label is for our docs team. Though have a README.md in the root of the plugin explaining what it does and what settings are available is always helpful.

please work on your conflicts and we’ll look at merging it Monday

2025-01-02 07:09 UTC, robin-rrt commented
@odilitime conflicts must be solved now

2025-01-05 07:57 UTC, merged