feature: news-plugin
elizaOS/eliza pull request #1248
Opened 2024-12-19 20:30 UTC by ileana-pr

# Relates to:
AI Agent Dev School Video #2: https://www.youtube.com/watch?v=XenGeAcPAQo&t=3383s 

# Risks

Low 

# Background
Shaw shows us how to create a simple plugin that returns the latest news on a specific topic. This is an example code of a completed currentNewsAction. It can be modified and expanded for added functionality. 

## What does this PR do?

Adds an example of the news plugin described by Shaw. 

## What kind of change is this?

Features 

It will help future students to see an example of the code and more experienced devs to add functionality to a useful plugin. 

# Documentation changes needed?

none, but I can add documentation 

# Testing

I tested the plugin with C3PO character and was able to retrieve news on different topics. 

Formatting of the output can use some improvement. 

## Where should a reviewer start?

news.ts 

## Detailed testing steps

2025-01-02 00:35 UTC, ileana-pr commented
@odilitime @shakkernerd added README.md documentation, updated output format & tested. 
![Screenshot 2025-01-01 193116](https://github.com/user-attachments/assets/330de579-80b0-4e23-b961-b4b893a57fc0)
![Screenshot 2025-01-01 190517](https://github.com/user-attachments/assets/0483840f-a817-42d6-818c-522cbb46ea41)

2025-01-11 03:59 UTC, ileana-pr commented
gm @odilitime @shakkernerd , anything I can fix or do to help get this plugin merged? thanks.

2025-01-11 04:14 UTC, tcm390 requested changes
LGTM. Just some small change requests

2025-01-11 04:14 UTC, tcm390 commented on agent/src/index.ts
> +import { intifacePlugin } from "@ai16z/plugin-intiface";
are you using this?

2025-01-13 01:43 UTC, ileana-pr commented on agent/src/index.ts
> +            newsPlugin,
@tcm390 all done and ready for review. thank you.

2025-01-23 21:46 UTC, shakkernerd commented
@ileana-pr kindly resolve the conflicts on this.

2025-01-24 18:01 UTC, ileana-pr commented
@shakkernerd conflicts resolved. Thanks much.

2025-01-26 06:19 UTC, shakkernerd approved these changes

2025-01-26 06:21 UTC, merged