add thirdweb plugin
elizaOS/eliza pull request #1418
Opened 2024-12-24 02:33 UTC by iankm

Adding a new plugin for thirdweb's nebula API. We have one action that interacts with our natural language interface to read data from 2000+ blockchains.

Added, Readme, .env config and integration to default agent if key is set.

Here's an image with example usage (through my agent, Breakout Bro):

<img width="1105" alt="CleanShot 2024-12-23 at 21 32 14@2x" src="https://github.com/user-attachments/assets/92ca64ea-ba89-408b-a7c6-704d32ea8ebc" />

2024-12-24 12:44 UTC, samarth30 requested changes
Looks solid to me just tested it out. 
Let's resolve conflitcs in the branch and get it merged.

2024-12-24 13:39 UTC, iankm commented
Hey @samarth30,

Addressed the merge conflicts!

2024-12-24 23:47 UTC, odilitime submitted a review, later dismissed

2025-01-03 22:04 UTC, ianthirdweb commented
@odilitime @samarth30 updated to use the @elizaos package identifier

2025-01-07 21:51 UTC, fabianhug commented
gm @iankm 

if you merge this one, we *should* be good to go 

https://github.com/iankm/eliza/pull/1

thx

2025-01-08 01:27 UTC, merged