Add: Client Reddit Files
elizaOS/eliza pull request #1445
Opened 2024-12-25 05:18 UTC by Freytes

# @ai16z/client-reddit

A powerful Reddit client plugin for the Eliza framework that enables AI agents to interact with Reddit through posting, commenting, and voting capabilities.

## Features

* Full Reddit API integration via Snoowrap wrapper
* Create and submit posts to multiple subreddits
* Comment on existing posts and replies
* Vote on posts and comments programmatically
* Automated posting with configurable intervals
* Built-in rate limiting and error handling
* Dry run mode for testing
* TypeScript support out of the box

## Installation

```bash
npm install @ai16z/client-reddit
```

Or using yarn:

```bash
yarn add @ai16z/client-reddit
```

## Configuration

### Required Environment Variables

```env
REDDIT_CLIENT_ID=your_client_id
REDDIT_CLIENT_SECRET=your_client_secret
REDDIT_REFRESH_TOKEN=your_refresh_token
REDDIT_USER_AGENT=your_user_agent
REDDIT_SUBREDDITS=subreddit1,subreddit2,subreddit3
```

### Optional Configuration

```env
REDDIT_AUTO_POST=true           # Enable automated posting
POST_INTERVAL_MIN=90           # Minimum time between posts (minutes)
POST_INTERVAL_MAX=180          # Maximum time between posts (minutes)
POST_IMMEDIATELY=false         # Post on startup
REDDIT_DRY_RUN=false          # Run without making actual API calls
```

## Usage

### As an Eliza Plugin

```typescript
import { redditPlugin } from '@ai16z/client-reddit';
import { Eliza } from '@ai16z/eliza';

const eliza = new Eliza();
eliza.use(redditPlugin);

// The plugin will automatically initialize with your environment variables
```

### Direct Usage

```typescript
import { RedditClient } from '@ai16z/client-reddit';

const client = new RedditClient(runtime);
await client.start();

// Submit a post
await client.submitPost('subreddit', 'Title', 'Content');

// Create a comment
await client.createComment('t3_postId', 'This is a comment');

// Vote on content
await client.vote('t3_postId', 1); // 1 for upvote, -1 for downvote
```

## Available Actions

### Create Post

```typescript
runtime.execute('CREATE_REDDIT_POST', {
  content: {
    subreddit: 'test',
    title: 'My First Post',
    text: 'This is the content of my post'
  }
});
```

### Create Comment

```typescript
runtime.execute('CREATE_REDDIT_COMMENT', {
  postId: 't3_abc123',
  content: 'This is my comment'
});
```

### Vote

```typescript
runtime.execute('REDDIT_VOTE', {
  targetId: 't3_abc123',
  direction: 1  // 1 for upvote, -1 for downvote
});
```

## Error Handling

The client includes built-in error handling for common Reddit API issues:

* Rate limiting
* Invalid credentials
* Network errors
* Subreddit posting restrictions
* Content filters

Errors are logged and can be caught using standard try/catch blocks.

2024-12-25 07:16 UTC, odilitime commented
needs to include the agent/ wiring (package.json src/index.ts)

2024-12-25 12:41 UTC, Freytes commented
@odilitime Updated the requested files.

2024-12-25 22:21 UTC, odilitime approved these changes, later dismissed

2024-12-26 00:17 UTC, shakkernerd commented
You need to rebase your main, seems like some changes are missing in your fork.

2024-12-28 05:57 UTC, odilitime commented
Tried to resolve conflicts but looks like `src/agent/index.ts` is missing some updates from develop, we can't merge until those regressions are fixed.

2024-12-28 05:59 UTC, odilitime requested changes

2024-12-28 05:59 UTC, odilitime commented on agent/src/index.ts
> +    elizaLogger.debug(JSON.stringify(options, null, 2));
this shouldn't be enabled

2024-12-28 05:59 UTC, odilitime commented on agent/src/index.ts
all these regressions needs to be fixed

2025-01-02 19:38 UTC, houssemmechri commented on agent/src/index.ts
> +import { RedditClientInterface } from "@elizaos/plugin-reddit";
this should be client-reddit instead of plugin-reddit

2025-01-09 12:27 UTC, timmyg commented
@Freytes  why did this get closed?

2026-08-13 01:20 UTC, closed without merging