feat: Twitter Spaces Integration
elizaOS/eliza pull request #1550
Opened 2024-12-29 02:44 UTC by slkzgm

# feat: Twitter Spaces Integration

**Discord**: `slkz.`

## Overview

This PR introduces integration of **Twitter Spaces** into the AI agent, providing:
- **Automatic** Space launch decisions (random chance, business hours, cooldown intervals, etc.).
- **Multi-speaker** handling (configurable `maxSpeakers`).
- **Speaker queue** management for overflow.
- **GPT-based filler** messages (welcome, idle, closing, etc.).
- Optional **plugins**: Idle monitor, TTS bridging (STT/TTS), and local audio recording.

No breaking changes are introduced beyond **adding** this new functionality and **updating** the `agent-twitter-client` to support advanced speaker logic.

---

## Flow Recap

1. **Periodic Check**  
   We call `startPeriodicSpaceCheck()`, typically with a dynamic interval.  
   - **When no Space is running**: we do `shouldLaunchSpace()`, which decides whether to launch based on random chance, business hours, and a minimum cooldown.  
   - **When a Space is running**: we call `manageCurrentSpace()` more frequently (e.g. every 20 seconds) to handle speaker timeouts, queue acceptance, occupancy changes, and potential stop conditions.

2. **Space Creation**  
   - We generate a `SpaceConfig` from either pre-set `charSpaces.topics` or GPT (if none are provided).  
   - We instantiate a new `Space`, conditionally add:
     - **RecordToDiskPlugin** (audio recording to disk).
     - **SttTtsPlugin** (speech-to-text and text-to-speech bridging).
     - **IdleMonitorPlugin** (idle detection).  
   - We hook into events: `speakerRequest`, `occupancyUpdate`, `idleTimeout`, etc.

3. **Speaker Logic**  
   - We maintain an **array** of `activeSpeakers` and a **queue** for overflow if `activeSpeakers.length` hits `maxSpeakers`.  
   - Each speaker is subject to `speakerMaxDurationMs`; upon exceeding it, we remove them (optionally speaking a filler message).  
   - If a speaker is removed and the queue is **non-empty**, we accept the next queued request.  
   - If more than `maxSpeakers` are active for any reason, we remove extras.

4. **Stopping**  
   - `stopSpace()` finalizes the Space, logs the time of completion (`lastSpaceEndedAt`), clears states, and sets `isSpaceRunning = false`.  
   - The system then reverts to checking at a slower interval until we decide to launch a new Space again.

---

## Configuration

### A) `.env` / Environment Variables

If you want to store GPT or ElevenLabs tokens:
```bash
OPENAI_API_KEY=sk-...
ELEVENLABS_API_KEY=...
```
### B) `character.json` → `"twitterSpaces"` Field

Below is an **example** JSON snippet for the `twitterSpaces` object in `character.json`:

```jsonc
{
  // ...
  "twitterSpaces": {
    // Maximum simultaneous speakers (1 = single speaker, 2+ = multi)
    "maxSpeakers": 2,

    // Array of predefined topic strings
    // If empty, we use GPT to generate some
    "topics": [
      "Blockchain Trends",
      "AI Innovations"
    ],

    // Max overall duration (in minutes) for the Space
    "typicalDurationMinutes": 45,

    // Idle threshold in ms (e.g., 300000 = 5 minutes)
    "idleKickTimeoutMs": 300000,

    // Minimum interval (minutes) before launching another Space
    "minIntervalBetweenSpacesMinutes": 60,

    // If true, only launch between 9:00-17:00 UTC
    "businessHoursOnly": true,

    // Probability (0.0 - 1.0) at each check
    "randomChance": 0.3,

    // Flags to enable or disable specific plugins
    "enableIdleMonitor": true,
    "enableSttTts": true,
    "enableRecording": false,

    // TTS / GPT config (e.g., for ElevenLabs)
    "voiceId": "21m00Tcm4TlvDq8ikWAM",
    "sttLanguage": "en",
    "gptModel": "gpt-3.5-turbo",
    "systemPrompt": "You are a helpful AI co-host assistant.",

    // Max speaking time (ms) for each speaker
    "speakerMaxDurationMs": 240000
  }
}
```

**Key Fields**:
- **`maxSpeakers`**: 1 for single-speaker style, or higher to allow multiple.  
- **`topics`**: if empty, GPT auto-generates.  
- **`idleKickTimeoutMs`**: triggers `idleTimeout` if no audio detected for that duration.  
- **`randomChance`**: probability for each check to spawn a Space.  
- **`speakerMaxDurationMs`**: automatically remove a speaker after this many ms.  

---

## Potential Improvements

- **Audio Message Queue**: Manage TTS outputs in a queue to avoid overlapping messages.  
- **Knowledge Storage**: Gather insights from Space interactions and store them as knowledge or memory afterwards.  
- **Speaker-less Spaces**: Optionally launch Spaces without external speakers, functioning as “TED talk” monologues or scheduled broadcasts.

---

## Additional Notes

- This is our **first** official integration of Twitter Spaces, not an upgrade from a previous version.  
- **No Breaking Changes** expected outside the new `agent-twitter-client` version.  
- For questions, you can reach me on Discord: `slkz.`

Thank you!

2024-12-29 19:48 UTC, odilitime requested changes
please add back the documentation

2024-12-29 19:48 UTC, odilitime commented on packages/client-twitter/src/environment.ts
why are you removing comments and documentation?

2024-12-29 23:09 UTC, slkzgm commented on packages/client-twitter/src/environment.ts
didn't though it was useful, added back!

2025-01-01 12:13 UTC, lalalune commented
Some conflicts that need review, we should prioritize getting this in since it's a pretty big push

2025-01-01 13:22 UTC, merged