feat: added zktls - reclaim
elizaOS/eliza pull request #1558
Opened 2024-12-29 07:41 UTC by Gajesh2007

# Risks

Low

# Background

A few weeks ago, we observed issues with aixbt, where users mistakenly believed the moderation was performed by humans. This misconception caused a public relations disaster and raised concerns about the AI's autonomy. As a result, the team had to make logs public to maintain transparency and trust.

This problem can be mitigated using zkTLS. zkTLS enables the generation of zero-knowledge proofs for TLS sessions, also known as "web proofs." With zkTLS, any off-chain data can be proven either on-chain or off-chain, ensuring authenticity without compromising privacy.

## What does this PR do?

This PR integrates Reclaim as an adapter into the framework without introducing breaking changes. Reclaim is a zkTLS platform built on EigenLayer as an Actively Validated Service (AVS).

## What kind of change is this?
Updates 
-->

## Why are we doing this? Any context or related work?

This update addresses the critical need for transparency and trust in AI interactions, as highlighted by the PR disaster involving aixbt. By integrating **Reclaim** as a zkTLS adapter, we ensure that all inferences and interactions are verifiable without compromising privacy. This addition strengthens the framework's credibility by enabling zero-knowledge proof generation and verification for TLS sessions.

The integration aligns with EigenLayer's mission to build secure and verifiable systems, leveraging **Actively Validated Services (AVS)** to enhance both functionality and trustworthiness. This is especially relevant as more AI systems require robust mechanisms to prove autonomy and authenticity in a seamless and privacy-preserving manner.

# Documentation changes needed?

Documentation has been updated in the adapter-reclaim README.
No further changes to the project documentation are required.

# Proof Verification Example
Below is a screenshot showcasing the generated proof and its verification process:

<img width="843" alt="Screenshot 2024-12-28 at 11 39 17 PM" src="https://github.com/user-attachments/assets/17c64b01-47b1-4ece-8624-9b65e7624f66" />

<img width="847" alt="Screenshot 2024-12-28 at 11 31 20 PM" src="https://github.com/user-attachments/assets/d41d675e-9249-4c46-9f12-396f02b7d8b2" />

# Testing

## Where should a reviewer start?

## Detailed testing steps

1. Configure the following environment variables (generated from the [Reclaim Dashboard](https://dev.reclaimprotocol.org/new-application)):
```
# Reclaim Protocol
RECLAIM_APP_ID= # Reclaim App ID
RECLAIM_APP_SECRET= # Reclaim App Secret

# Verifiable Inference Configuration
VERIFIABLE_INFERENCE_ENABLED=true # Set to true to enable verifiable inference
VERIFIABLE_INFERENCE_PROVIDER=reclaim # Options: reclaim, opacity (soon)
```

2. Run a character using the command:

`pnpm start --characters="./characters/trump.character.json"`

3. Start the client: `pnpm start:client`
4. Interact with the agent via chat and check the logs for proof generation and verification.

## Additional Notes
- Automated tests are sufficient; no manual testing is required for deployment.
- No database changes or additional deployment instructions are necessary.

## Discord username

--> Gajesh#0000

2024-12-29 19:09 UTC, fabianhug commented
testing now

2024-12-29 19:57 UTC, odilitime requested changes
This is not an adapter but a plugin. Adapters have to do with persist storage

2024-12-29 21:00 UTC, fabianhug commented
@odilitime, did you happen to test it thoroughly? I am running into some errors, and I wanted to clarify them first:

when `modelProvider` is set to `openai`: 
```Error in Reclaim generateText: Error: Failed to create claim on witness: request body mismatch```

when `modelProvider` is set to `anthropic`: 
```Error in Reclaim generateText: Error: Invalid receipt. Regex "\r\n\r\n[a-f0-9]+\r\n(?<response>\{.*\})" didn't match```


@Gajesh2007

2024-12-29 21:41 UTC, Gajesh2007 commented
let me look into it

2024-12-30 23:18 UTC, fabianhug commented
> let me look into it

we would love to add this in the next release :)

2025-01-02 02:16 UTC, fabianhug commented
any update? @Gajesh2007

2025-01-02 10:53 UTC, Gajesh2007 commented
hey! looking into it today morning.

Regards,

Gajesh Naik


On Wed, 1 Jan 2025 at 6:17 PM, Fabian Hug ***@***.***> wrote:

> any update? @Gajesh2007 <https://github.com/Gajesh2007>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/elizaOS/eliza/pull/1558#issuecomment-2567229293>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGJVDIW4MU7CFZPDIJOAFXT2ISOSZAVCNFSM6AAAAABUKRXFMGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRXGIZDSMRZGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-01-05 05:50 UTC, Gajesh2007 commented
debugged the anthropic issue and re-ran the openai one. 

it works now but im not sure why install dependencies is not working on ci/cd. 

 
<img width="728" alt="Screenshot 2025-01-04 at 9 49 44 PM" src="https://github.com/user-attachments/assets/185f52d7-570b-4053-b37a-cfe2435525a9" />

2025-01-06 00:17 UTC, merged

2025-01-06 00:17 UTC, fabianhug commented
great collaboration via TG @Gajesh2007 
thanks for your contribution!