feat: FereAI integration and ferePro plugin update
elizaOS/eliza pull request #1566
Opened 2024-12-30 02:20 UTC by sekmet

# Relates to:

- **FereAI integration – Adding structured ChatResponse handling**  
  Resolves: [https://github.com/elizaOS/eliza/issues/1405](https://github.com/elizaOS/eliza/issues/1405)  

- **Addition of FerePro Plugin**  
  Fixes: [https://github.com/elizaOS/eliza/pull/1502](https://github.com/elizaOS/eliza/pull/1502)  
  Fixes: [https://github.com/elizaOS/eliza/pull/1542](https://github.com/elizaOS/eliza/pull/1542)  

# Risks

**Low**

- **WebSocket Connection Handling**:  
  The `fereai-provider` manages all WebSocket connections internally, ensuring robust handling of connection stability and reconnections. 

- **API Credential Validation**:  
  If API credentials are missing or invalid, the provider handles errors gracefully, preventing application crashes.

- **Data Parsing**:  
  Potential parsing errors may occur if unexpected data formats are returned from the WebSocket API.

**Mitigation**:

- Implemented graceful error handling and logging within the `fereai-provider` to manage connection issues and invalid credentials.

- Provided fallback responses for invalid data formats to maintain application stability.

# Background

## What does this PR do?

This PR integrates the **FereAI APIs** using the `FereAI Provider for the Vercel AI SDK` module and update the **FerePro Plugin**, enhancing functionality to handle `ChatResponse` objects with better granularity. The primary changes are as follows:

1. **Integration of `FereAI Provider for the Vercel AI SDK`**:  
   - Added the `fereai-provider` module to support FereAI APIs. Environment variables `FEREAI_USER_ID` and `FEREAI_API_KEY` have been configured accordingly.
   - The provider is available in the `fereai-provider` module and has been installed using `pnpm add fereai-provider`.
   - Imported the default provider instance `fereai` from `fereai-provider` and integrated it into the core and agent system.
   - For more details, refer to the [fereai-provider repository](https://github.com/sekmet/fereai-provider).

2. **Addition of Helper Utilities and Structured Format Layers for `ChatResponse`**:  
   - Developed utilities to parse and handle `ChatResponse` objects, ensuring consistent formatting and error handling using Vercel AI SDK.

3. **Integration of `FerePro` Dependencies**:  
   - Enhanced extensibility for plugin responses and logs by incorporating `FerePro` dependencies into the **fereai-provider** module.

4. **Updates to Core Components**:  
   - Modified `packages/core/src/generation.ts` to support generatedText using Vercel AI SDK.
   - Modified `packages/core/src/models.ts` to support FereAI APIs using the model system.
   - Modified `packages/core/src/types.ts` the handle FereAI model.
   - Updated agent handlers to accommodate the new structured response handling.

## What kind of change is this?

**Features** | Added FerePro integration using `FereAI Provider for the Vercel AI SDK`.

# Documentation changes needed?

- [x] My changes do not require a change to the project documentation..  
  

# Testing

## Where should a reviewer start?

Begin by reviewing the integration of the `fereai-provider` in the `package.json` and the configuration of the required environment variables. Then, examine the updates made to `packages/core/src/generation.ts`, `packages/core/src/models.ts`, `packages/core/src/types.ts` and the `agent/src/index.ts` handlers under API configurations to understand the response handling.

## Detailed Testing Steps

1. **Setup Environment Variables**:  
   - Ensure that `FEREAI_USER_ID` and `FEREAI_API_KEY` are correctly set in the environment.

2. **Install Dependencies**:  
   - Run `pnpm add` to install the new `fereai-provider` module.

3. **Run Unit Tests**:  
   - Execute the `fereai-provider` test suite to verify that all existing and new tests pass successfully.
   - For `fereai-provider` tests, refer to the [fereai-provider tests](https://github.com/sekmet/fereai-provider/blob/main/packages/fereai/src/fereai.test.ts).

4. **Manual Testing**:  
   - Interact with the chatbot to ensure that responses are handled correctly and that the integration with FereAI APIs functions as expected using `fereai-provider`.
   - Monitor logs to confirm that structured logging is operational and that no errors related to the new integration occur.

# Deploy Notes

- **Environment Variables**:  
  - Ensure that `FEREAI_USER_ID` and `FEREAI_API_KEY` are set in the production environment.

- **Dependencies**:  
  - Install the `fereai-provider` module in the production environment using `pnpm add`.

## Database changes
- No database changes.

## Discord username
sekmet2600

2024-12-30 06:23 UTC, kritinyoupane commented
![image](https://github.com/user-attachments/assets/388eff3a-29a9-4bb6-8a9d-74d36f9e76f3)
I am having issues when doing pnpm build due to this plugin. How to solve this?

2024-12-30 18:13 UTC, odilitime requested changes
Does this replace #1542 if so, please close 1542

2024-12-30 18:13 UTC, odilitime commented on agent/src/index.ts
> +            getSecret(character, "FEREAI_API_KEY") ? fereProPlugin : null,
Why add the plugin twice?

2024-12-30 18:13 UTC, odilitime commented on scripts/start.sh
why add this empty file?

2024-12-30 18:48 UTC, sekmet commented
> Does this replace #1542 if so, please close 1542

I can't, It was opened by other developer.
I will message him asking to close it.

2024-12-30 18:49 UTC, sekmet commented on agent/src/index.ts
> +            getSecret(character, "FEREAI_API_KEY") ? fereProPlugin : null,
Fixed, just the User ID will work.

2024-12-30 18:53 UTC, sekmet commented on scripts/start.sh
Sorry about this, I just changed the permission to exec the script. I reverted the file permission back to 0664.

2024-12-30 20:48 UTC, sekmet commented on scripts/start.sh
Seems the file is still empty :(. Should I delete this file?

2025-02-04 14:19 UTC, sekmet commented
Hello @odilitime,
I will close this PR and open a new one to fill the current empty packages/plugin-ferePro plugin.

2026-08-13 01:21 UTC, closed without merging