bugfix. the port 80 is not listening use 3000
elizaOS/eliza pull request #1616
Opened 2024-12-31 18:19 UTC by jmikedupont2

3000 is listening on the docker image

# Risks

Low - This change affects the Docker container configuration. It may require updates to documentation and environment configurations where the container is deployed.

---

# Background

## What does this PR do?
This pull request updates the Dockerfile and related Docker configuration to expose port 3000 instead of port 80. This change is necessary to align with our application's configuration and avoid conflicts with other services running on port 80.

## What kind of change is this?

Bug fixes (non-breaking change which fixes an issue)

N/A (Issue linked provides context)

---

# Documentation changes needed?

My changes require a change to the project documentation. I have updated the documentation accordingly.

---

# Testing

## Where should a reviewer start?
Start by reviewing the changes in the Dockerfile and docker-compose.yml files.

## Detailed testing steps

1. Pull the latest changes from the repository.
2. Build the Docker image using the updated Dockerfile.
3. Run the container and verify that it is listening on port 3000.
4. Access the application through port 3000 to ensure it is functioning correctly.

---

N/A

N/A

N/A

docker build

## Discord username m1337d

2024-12-31 18:55 UTC, monilpat submitted a review, later dismissed
LGTM

2024-12-31 19:27 UTC, monilpat requested changes
Please revert the meta-introspector related changes unless that was intentional

2024-12-31 19:27 UTC, monilpat commented on .github/workflows/image.yaml
> +              uses: meta-introspector/checkout@v4
This should be reverted

2025-01-01 17:42 UTC, jmikedupont2 commented on .github/workflows/image.yaml
> +              uses: meta-introspector/checkout@v4
yes

2025-01-01 17:45 UTC, jmikedupont2 commented on .github/workflows/image.yaml
> +              uses: meta-introspector/checkout@v4
@monilpat done

2025-01-01 18:06 UTC, monilpat submitted a review, later dismissed
LGTM thanks for addressing comments :)

2025-01-01 19:19 UTC, HashWarlock approved these changes
LGTM

2025-01-04 05:03 UTC, merged

2025-01-04 05:05 UTC, jmikedupont2 commented
thanks yall, what a review process! I hope to have more substantial
patches, you can check this one i am working on.
https://github.com/meta-introspector/cloud-deployment-eliza/pull/1

On Sat, Jan 4, 2025, 00:03 Shakker Nerd ***@***.***> wrote:

> Merged #1616 <https://github.com/elizaOS/eliza/pull/1616> into develop.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/elizaOS/eliza/pull/1616#event-15812304731>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD5KQ2OP3EWTNMQSALKZWYD2I5TSNAVCNFSM6AAAAABUNYXS62VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJVHAYTEMZQGQ3TGMI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>