fix: don't reply to tweets older than 5 days
elizaOS/eliza pull request #454
Opened 2024-11-20 15:32 UTC by liamzebedee

# Relates to:

# Risks

# Background

## What does this PR do?

## What kind of change is this?

# Documentation changes needed?

# Testing

## Where should a reviewer start?

## Detailed testing steps

2024-11-20 16:22 UTC, monilpat commented
Also please resolve the conflicts :)

2024-11-20 16:24 UTC, monilpat requested changes
Thanks for working on this please address comments then good to go :)

2024-11-20 16:24 UTC, monilpat commented on core/src/clients/twitter/interactions.ts
> +
Great work - Can we make this configurable based off of each character. Adding a magic number will cause issues down the road. Please add this to the character.json under the settings and read from there and default to 5 days if nothing is passed in. Thanks so much!

2024-11-21 09:25 UTC, ponderingdemocritus commented
solid - fix issues then we can merge

2024-11-29 12:04 UTC, lalalune commented
This got overwritten by another branch so closing

2026-08-13 01:07 UTC, closed without merging