Add bob launchpad to icp package.
elizaOS/eliza pull request #714
Opened 2024-11-30 10:27 UTC by bob-robert-ai

Add https://launch.bob.fun, the most popular launchpad platform on ICP to the ICP package.

# Relates to:

Following this PR: https://github.com/ai16z/eliza/pull/357

# Risks

Low

2024-12-10 07:59 UTC, odilitime commented on packages/plugin-icp/src/actions/createToken.ts
> +            }, 'launch-bob');
why is this hard coded?

2024-12-10 07:59 UTC, odilitime commented on packages/plugin-icp/src/actions/createToken.ts
> -        }),
why are these taken out in this branch?

2024-12-14 11:08 UTC, lalalune commented
@bob-robert-ai there are some conflicts with some other ICP-related create token functionality, would you mind reviewing that?

2025-01-02 13:16 UTC, bob-robert-ai commented on packages/plugin-icp/src/actions/createToken.ts
> +            }, 'launch-bob');
launch.bob.fun is the most widely used launchpad on ICP, so it felt logical to set it as the default.

2025-01-02 13:24 UTC, bob-robert-ai commented on packages/plugin-icp/src/actions/createToken.ts
> -        }),
Added back.

2025-01-02 13:30 UTC, bob-robert-ai commented
> @bob-robert-ai there are some conflicts with some other ICP-related create token functionality, would you mind reviewing that?

Just fixed the conflicts, could you take a look?

2025-01-06 10:02 UTC, wtfsayo approved these changes
~~Low risk, ready to merge, integration test failing because `develop` is broken~~

2025-01-06 10:23 UTC, wtfsayo requested changes
Did a more thorough review. looks like competition between PickPump and LaunchBob... please submit a proper PR than trying to force replace yours!

2025-01-17 11:46 UTC, bob-robert-ai commented
How do you usually go about competing launchpads?

2026-08-13 01:07 UTC, closed without merging