base-ragsearch-plugin
elizaOS/eliza pull request #944
Opened 2024-12-09 19:04 UTC by alextitonis

# Relates to:

# Risks

# Background

## What does this PR do?

## What kind of change is this?

# Documentation changes needed?

# Testing

## Where should a reviewer start?

## Detailed testing steps

2024-12-27 07:27 UTC, samarth30 commented
@alextitonis I just reviewed this PR, and I have a suggestion:

This implementation seems more suited to being an Adapter, similar to existing ones like PostgreSQL, Supabase, or SQL Adapters. Could you refactor it into an Adapter with all the relevant functions required for seamless integration?

Additionally, to ensure usability and proper testing, could you include an example demonstrating how this Adapter can be used with an Agent Client for testing purposes? This will help verify the implementation and provide a practical use case.

2024-12-27 19:38 UTC, alextitonis commented
> @alextitonis I just reviewed this PR, and I have a suggestion:
> 
> This implementation seems more suited to being an Adapter, similar to existing ones like PostgreSQL, Supabase, or SQL Adapters. Could you refactor it into an Adapter with all the relevant functions required for seamless integration?
> 
> Additionally, to ensure usability and proper testing, could you include an example demonstrating how this Adapter can be used with an Agent Client for testing purposes? This will help verify the implementation and provide a practical use case.

It's not meant to be used as a normal database as it's using a graph for storing data, but as an extra layer, that's why i made it like that.
For use case, you can store some memories and draw connections and then use the query to get docs.
For example user X is base.
Chat with X on twitter is on graph, connected to base X
Chat with X on discord is another graph, connected to base
You can query both graphs.
Also will search node by node as well to using the embedding. (not sure if i explained correctly, if not let me know)

2024-12-28 07:24 UTC, samarth30 commented
Looks great to me! Could you integrate this plugin with the Agent Client, following the same approach used for other plugin integrations? 
can you also make a PR on Develop branch

2024-12-30 11:47 UTC, alextitonis commented
> Looks great to me! Could you integrate this plugin with the Agent Client, following the same approach used for other plugin integrations? can you also make a PR on Develop branch

Tried to follow the other plugins, is there something wrong? can fix it. 
Will do the other PR as well

2024-12-30 12:55 UTC, samarth30 commented
Hi @alextitonis,

Could you include the plugin initialization in agent/src/index.ts, similar to how the other plugins have been integrated? This will ensure consistency across the project.

Also, it might be a good idea to define some actions so your plugin can be utilized effectively. By attaching the plugin to specific actions, it can seamlessly integrate into the workflow. Let me know if you’d like any support with this!

2024-12-31 12:40 UTC, alextitonis commented
> Hi @alextitonis,
> 
> Could you include the plugin initialization in agent/src/index.ts, similar to how the other plugins have been integrated? This will ensure consistency across the project.
> 
> Also, it might be a good idea to define some actions so your plugin can be utilized effectively. By attaching the plugin to specific actions, it can seamlessly integrate into the workflow. Let me know if you’d like any support with this!

Rebased to developer and added initialization, would be perfect if you could help with the action example

2025-01-06 16:55 UTC, wtfsayo commented
>would be perfect if you could help with the action example

https://github.com/elizaOS/eliza/blob/8205313071203e2610c9817839503f60919f7a40/packages/plugin-image-generation/src/index.ts#L65

2025-01-06 16:56 UTC, wtfsayo requested changes
Please add actions to make it work!

2025-01-09 13:20 UTC, alextitonis commented
@wtfsayo @samarth30 added an action

2025-01-14 03:41 UTC, wtfsayo commented
@coderabbitai review

2025-02-21 04:11 UTC, closed without merging