feat: implemented eliza chatbot
elizaOS/eliza pull request #971
Opened 2024-12-10 12:59 UTC by salmanpot

i have created the feature in which we extract the tweets from the twitter globally from the twitter Api and by using these trends and the dumy data that we have created to test both concat and give to our LLM model in which LLM model give the response according to the character file that we made.

2024-12-10 15:59 UTC, odilitime requested changes

2024-12-10 15:59 UTC, odilitime commented on agent/.gitignore
Revert or explain why this is necessary

2024-12-10 15:59 UTC, odilitime commented on agent/src/services/twitter/services.ts
> +    const pdfFilePath = "C:/Users/Dell/eliza-1/agent/src/services/twitter/game.pdf";  //a dummy pdf
no hard coded paths, node has __dirname if you want to give a relative path to this file
https://nodejs.org/docs/latest/api/globals.html#__dirname

2024-12-10 15:59 UTC, odilitime commented on characters/trump.character.json
I'm not sure we should be deleting our sample characters without replacing them

2024-12-10 16:02 UTC, odilitime requested changes

2024-12-10 16:02 UTC, odilitime commented on agent/src/providers/twitter.ts
src/providers isn't probabaly the best place for this, belongs in it's own plugin

2024-12-10 16:02 UTC, odilitime commented on agent/src/services/twitter/services.ts
src/providers isn't probabaly the best place for this, belongs in it's own plugin

2024-12-11 11:43 UTC, salmanpot commented
1- The decision to empty agent/.gitignore was made because when attempting
to push the code to GitHub, .ts files were being included, which caused
conflicts and prevented the latest code from being pushed successfully. A
main .gitignore file has already been created at the root level, which
contains all the necessary exclusions, including those for .ts files. This
eliminates the need for a separate .gitignore file in the agent/ folder.

2- I have corrected the hardcoded path issue by replacing it with a
relative path using __dirname for better portability and maintainability.

3-I understand the concern about deleting sample characters. To test our
sports analysis functionality, I temporarily replaced the sample character
file but have since reverted it back. Rest assured, I have all the original
sample files, including the personality you provided and the ones we tested.

On Tue, 10 Dec 2024 at 12:00, Odilitime ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On agent/.gitignore
> <https://github.com/ai16z/eliza/pull/971#discussion_r1878363005>:
>
> Revert or explain why this is necessary
> ------------------------------
>
> In agent/src/services/twitter/services.ts
> <https://github.com/ai16z/eliza/pull/971#discussion_r1878369796>:
>
> > +// Load environment variables from .env file
> +dotenv.config();
> +
> +// Define constants
> +const BEARER_TOKEN = process.env.BEARER_TOKEN;
> +const BASE_URL = "https://api.twitter.com/2/tweets/search/recent";
> +
> +/**
> + * Fetch recent tweets related to sports.
> + * @param maxResults Number of tweets to fetch (default: 10)
> + */
> +
> +// this function will get data from documnets for buliding custom knowledge base
> +export const fetchDocuments = async (): Promise<string[]> => {
> +    const pdfService = new PdfService();
> +    const pdfFilePath = "C:/Users/Dell/eliza-1/agent/src/services/twitter/game.pdf";  //a dummy pdf
>
> no hard coded paths, node has __dirname if you want to give a relative
> path to this file
> https://nodejs.org/docs/latest/api/globals.html#__dirname
> ------------------------------
>
> On characters/trump.character.json
> <https://github.com/ai16z/eliza/pull/971#discussion_r1878371462>:
>
> I'm not sure we should be deleting our sample characters without replacing
> them
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ai16z/eliza/pull/971#pullrequestreview-2492783366>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A25IBTDKIAJAXDO3DUXL2E32E4FYHAVCNFSM6AAAAABTLDQIYOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOJSG44DGMZWGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-11 15:58 UTC, odilitime commented
1. That makes sense for the .ts changes what about the data/ and generatedImages/

2. Will check it out when you push the code for that

3. Will check it out when you push the code for that

2024-12-14 11:06 UTC, lalalune commented
As we are refactoring, I'm gonna close this since it is a lot of unintended consequences and changes

2026-08-13 01:07 UTC, closed without merging